version: '3.3'

services:
  client:
    restart: always
    build: client/
    links:
      - server
    environment:
      - REACT_APP_APIS=https://home.yooooomi.com/searcher_api,https://192.168.1.6/searcher_api
    ports:
      - "3000:3000"

  server:
    build: server/
    restart: always
    environment:
      - CORS_WHITELIST=all
    volumes:
      - /home/ubuntu/Documents/torrents/downloads/torrents:/data:z
      - ./config/:/app/config
    ports:
      - "8081:8081"
