version: '3'

services:
  client:
    build: client/
    environment:
      - REACT_APP_API=server
    links:
      - mongo
    ports:
      - "3000:3000"

  server:
    build: server/
    environment:
      - CORS_WHITELIST=http://localhost:5000,http://localhost:3000
      - DOMAIN=.
    ports:
      - "8081:8081"