version: '3.3'

services:
  server:
    build: server/
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - CORS_WHITELIST=all
    volumes:
      - /home/ubuntu/Documents/torrents/downloads/torrents:/data:z
      - ./config/:/config
    ports:
      - "8081:8081"
