version: '3.3'

services:
  client:
    build: client/
    links:
      - server
    environment:
      - REACT_APP_APIS=http://domainname:8081,http://192.168.1.6:8081
    ports:
      - "3000:3000"

  server:
    build: server/
    environment:
      - CORS_WHITELIST=http://localhost:5000,http://localhost:3000
    volumes:
      - /home/pi/Documents/torrents/downloads:/data:z
      - ./config/:/app/config
    ports:
      - "8081:8081"
