version: '3.3'

services:
  client:
    build: client/
    links:
      - server
    environment:
      - REACT_APP_API=http://server:8081
    ports:
      - "3000:3000"

  server:
    build: server/
    environment:
      - CORS_WHITELIST=http://localhost:5000,http://localhost:3000
    volumes:
      - /home/timothee/Downloads:/app/downloads:z
      - config/:/app/config
    ports:
      - "8081:8081"
