version: '3.3'

services:
  server:
    build: server/
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - CORS_WHITELIST=all
    volumes:
      # - ./torrents:/data
      - /home/ubuntu/Documents/torrents/downloads/torrents:/data
      - ./config/:/app/config
    ports:
      - "8002:8081"
